apiVersion: v1
kind: Service
metadata:
  name: hrms-backend
  namespace: hrms
  labels:
    app: hrms-backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: hrms-backend
