apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hrms

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - redis-deployment.yaml
  - rabbitmq-statefulset.yaml
  - kafka-deployment.yaml
  - n8n-deployment.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-hpa.yaml
  - frontend-deployment.yaml
  - ingress.yaml
