apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrms-redis
  namespace: hrms
  labels:
    app: hrms-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hrms-redis
  template:
    metadata:
      labels:
        app: hrms-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: hrms-redis
  namespace: hrms
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: hrms-redis
