apiVersion: v1
kind: Secret
metadata:
  name: hrms-secrets
  namespace: hrms
type: Opaque
stringData:
  SECRET_KEY: "change-this-in-production-super-secret-django-key"
  MONGO_URI: "mongodb+srv://admin:password@cluster.mongodb.net/hrms_db?retryWrites=true&w=majority"
  CLOUDINARY_CLOUD_NAME: "your_cloud_name"
  CLOUDINARY_API_KEY: "your_api_key"
  CLOUDINARY_API_SECRET: "your_api_secret"
  RABBITMQ_PASSWORD: "guest"
  N8N_WEBHOOK_SECRET: "hrms-n8n-secure-token"
